default_agent: smart_home_assistant
agents:
  smart_home_assistant:
    name: smart_home_assistant
    entrypoint: /Users/wongxiao/strands-chatbot/agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/wongxiao/strands-chatbot
    aws:
      execution_role: arn:aws:iam::671067840733:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-d4f0bc5a29
      execution_role_auto_create: false
      account: '671067840733'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-671067840733-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: smart_home_assistant-nBHKspHdLI
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:671067840733:runtime/smart_home_assistant-nBHKspHdLI
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
